language: java

jdk:
  - openjdk17

sudo: false

env:
  global:
    - CODECOV_TOKEN='bce4e327-b746-4237-bcd4-35dcc518df80'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -s595659@mail.ru
    on_success: never # default: change
    on_failure: always # default: always